### ISSUE TITLE
When docserv2 gets multiple build instructions at once, it also stitches multiple times

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#177]
Instructing e.g.:

```
[{"target":"test","product":"sles","docset":"15-GA","lang":"en-us"},{"target":"test","product":"sles","docset":"15-GA","lang":"de-de"},{"target":"test","product":"sles","docset":"15-GA","lang":"es-es"}]
```

We also stitch three times in a row. That makes absolutely no sense beyond wasting time.

**Comment by sknorr** [comment]
This can lead to issues too, such as this docset that was not built because the stitch failed:

```
2021-05-14 09:20:18,582 - DEBUG - Stitching of /etc/docserv/config.d/ successful
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/docserv/docserv.py", line 405, in worker
    self.parse_build_instruction(thread_id)
  File "/usr/lib/python3.6/site-packages/docserv/docserv.py", line 234, in parse_build_instruction
    build_instruction, self.config, self.stitch_tmp_dir, self.gitLocks, self.gitLocksLock, thread_id)
  File "/usr/lib/python3.6/site-packages/docserv/bih.py", line 66, in __init__
    if not self.read_conf_dir():
  File "/usr/lib/python3.6/site-packages/docserv/bih.py", line 360, in read_conf_dir
    self.tree = etree.parse(self.stitch_tmp_file)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/tmp/docserv_stitch_zxbeip0_/productconfig_simplified_doc-suse-com.xml", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

2021-05-14 09:20:18,594 - DEBUG - Cleaning up after "fd07d6ade" (success)
```
