### ISSUE TITLE
ds2: `OSError: [Errno 24] Too many open files`

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#199]
While I was happily trying to build all of SLES & SLED in a languages, this happened^. I was less happy thereafter.

**Comment by sknorr** [comment]
As we use `subprocess` a bit, this might be related: https://stackoverflow.com/questions/16526783

**Comment by sknorr** [comment]
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/sknorr/gits/docserv/src/docserv/docserv.py", line 400, in worker
    deliverable.run(thread_id)
  File "/data/sknorr/gits/docserv/src/docserv/deliverable.py", line 206, in run
    self.iterate_commands(commands, n, thread_id)
  File "/data/sknorr/gits/docserv/src/docserv/deliverable.py", line 220, in iterate_commands
    result = self.execute(commands[i], thread_id)
  File "/data/sknorr/gits/docserv/src/docserv/deliverable.py", line 237, in execute
    stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1234, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by sknorr** [comment]
Setting `ulimit -n 4096` is my current approach/workaround.

**Comment by sknorr** [comment]
I guess we could write the following into /etc/security/limits.conf during package installation if that is not too evil:
```
docserv soft     nofile         65535   
docserv hard     nofile         65535
```

**Comment by sknorr** [comment]
bf462e1 fixes the issue.
