### ISSUE TITLE
BIH clean up traces back when stitch fails

### ISSUE THREAD

**Issue by sknorr** [openSUSE/docserv#76]
this happens during BIH-clean-up after stitching fails, and then of course there is no cache dir to clean up and the variable is not defined yet:

```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/gits/docserv/src/docserv/bih.py", line 147, in __del__
    self.cleanup()
  File "/gits/docserv/src/docserv/bih.py", line 105, in cleanup
    self.deliverable_cache_base_dir,
AttributeError: 'BuildInstructionHandler' object has no attribute 'deliverable_cache_base_dir'
```

**Comment by eliroca** [comment]
Fixed with #176
